export type Category = 'war' | 'politics' | 'nature';
export interface HistoricalEvent { id: string; title: string; start: number; end?: number; category: Category; location: string; summary: string; facts: string[]; article: string; }
const entries: [string, number, number | undefined, Category, string, string, string[], string][] = [
['Guerres médiques',-490,-479,'war','Grèce · Empire perse','Les cités grecques affrontent les expéditions perses. Leur résistance transforme les rapports de force en mer Égée.',['490 av. J.-C. : bataille de Marathon.','480 av. J.-C. : Thermopyles et Salamine.','479 av. J.-C. : victoire grecque à Platées.'],'Guerres_médiques'],
['Guerre du Péloponnèse',-431,-404,'war','Grèce','Athènes et Sparte, à la tête de deux alliances, s’affrontent pour la domination du monde grec.',['Une guerre entre la ligue de Délos et la ligue du Péloponnèse.','L’expédition athénienne en Sicile se termine par un désastre.','404 av. J.-C. : capitulation d’Athènes.'],'Guerre_du_Péloponnèse'],
['Éruption du Vésuve',79,undefined,'nature','Italie','Une éruption ensevelit Pompéi et Herculanum. Les vestiges conservés offrent un témoignage exceptionnel de la vie romaine.',['Pompéi est recouverte de matériaux volcaniques.','Herculanum est frappée par des coulées pyroclastiques.','La date exacte de l’éruption reste discutée.'],'Éruption_du_Vésuve_en_79'],
['Guerre de Cent Ans',1337,1453,'war','France · Angleterre','Une succession de conflits oppose les couronnes française et anglaise, sur fond de rivalités dynastiques et territoriales.',['1346 : bataille de Crécy.','1429 : Jeanne d’Arc contribue à lever le siège d’Orléans.','1453 : bataille de Castillon.'],'Guerre_de_Cent_Ans'],
['Guerre de Trente Ans',1618,1648,'war','Europe','Un conflit né dans le Saint-Empire devient une guerre européenne mêlant tensions religieuses et rivalités politiques.',['1618 : défenestration de Prague.','La Suède puis la France interviennent dans le conflit.','1648 : traités de Westphalie.'],'Guerre_de_Trente_Ans'],
['Séisme de Lisbonne',1755,undefined,'nature','Portugal · Atlantique','Le 1er novembre, un séisme, un tsunami et des incendies dévastent Lisbonne et frappent d’autres côtes de l’Atlantique.',['La catastrophe survient le jour de la Toussaint.','La reconstruction transforme l’urbanisme de Lisbonne.','L’événement nourrit les débats des philosophes des Lumières.'],'Séisme_de_1755_à_Lisbonne'],
['Guerre de Sept Ans',1756,1763,'war','Europe · Amériques · Asie','Des puissances européennes s’affrontent sur plusieurs continents, avec des conséquences majeures pour leurs empires coloniaux.',['La guerre concerne aussi l’Amérique du Nord et l’Inde.','La Grande-Bretagne et la France s’opposent outre-mer.','1763 : traités de Paris et d’Hubertusbourg.'],'Guerre_de_Sept_Ans'],
['Monarchie constitutionnelle',1791,1792,'politics','France','La Constitution de 1791 limite le pouvoir royal. L’expérience s’achève avec la chute de la monarchie.',['1791 : adoption de la première Constitution écrite française.','Le pouvoir législatif est confié à une assemblée.','10 août 1792 : chute de la monarchie.'],'Monarchie_constitutionnelle_française_(1791–1792)'],
['Première République',1792,1804,'politics','France','La République succède à la monarchie. Convention, Directoire et Consulat se succèdent jusqu’à l’instauration de l’Empire.',['21 septembre 1792 : abolition de la royauté.','1795 : début du Directoire.','1799 : coup d’État du 18 Brumaire.'],'Première_République_(France)'],
['Guerres napoléoniennes',1803,1815,'war','Europe · Monde','La France napoléonienne affronte plusieurs coalitions. Ses conquêtes puis ses défaites redessinent l’Europe.',['1805 : bataille d’Austerlitz.','1812 : campagne de Russie.','1815 : défaite de Waterloo ; le début de cette période varie selon les historiens.'],'Guerres_napoléoniennes'],
['Premier Empire',1804,1814,'politics','France','Napoléon Bonaparte devient empereur des Français. Son régime centralisé accompagne une expansion militaire en Europe.',['1804 : proclamation de l’Empire.','Le Code civil est promulgué la même année.','1814 : première abdication ; bref retour pendant les Cent-Jours en 1815.'],'Premier_Empire'],
['Restauration',1814,1830,'politics','France','Les Bourbons retrouvent le trône avec Louis XVIII puis Charles X, dans le cadre d’une monarchie régie par une charte.',['1814 : Charte constitutionnelle.','La période est interrompue par les Cent-Jours en 1815.','1830 : les Trois Glorieuses renversent Charles X.'],'Restauration_(histoire_de_France)'],
['Monarchie de Juillet',1830,1848,'politics','France','Louis-Philippe devient roi des Français. Le régime conserve un suffrage censitaire et tombe lors de la révolution de février.',['1830 : arrivée au pouvoir de Louis-Philippe.','Le droit de vote dépend du niveau d’impôt.','1848 : abdication du roi.'],'Monarchie_de_Juillet'],
['Deuxième République',1848,1852,'politics','France','La révolution de février ouvre une nouvelle expérience républicaine, marquée par le suffrage universel masculin.',['1848 : abolition de l’esclavage dans les colonies françaises.','Louis-Napoléon Bonaparte est élu président.','1851 : coup d’État, avant la proclamation de l’Empire en 1852.'],'Deuxième_République_(France)'],
['Second Empire',1852,1870,'politics','France','Napoléon III gouverne un Empire d’abord autoritaire, puis progressivement libéralisé, sur fond de transformations économiques.',['1852 : proclamation du Second Empire.','Paris est transformé sous la direction d’Haussmann.','1870 : défaite de Sedan et chute du régime.'],'Second_Empire'],
['Troisième République',1870,1940,'politics','France','Un régime parlementaire s’enracine durablement. Il traverse la Première Guerre mondiale et s’effondre lors de la défaite de 1940.',['1875 : lois constitutionnelles.','1905 : séparation des Églises et de l’État.','1940 : vote des pleins pouvoirs à Pétain.'],'Troisième_République_(France)'],
['Éruption du Krakatoa',1883,undefined,'nature','Indonésie','L’explosion du volcan Krakatoa, en août, provoque des tsunamis dévastateurs et des effets atmosphériques à grande distance.',['26–27 août : phase paroxysmale de l’éruption.','Les tsunamis frappent les côtes de Java et Sumatra.','Les poussières volcaniques affectent l’atmosphère mondiale.'],'Éruption_du_Krakatoa_en_1883'],
['Première Guerre mondiale',1914,1918,'war','Europe · Monde','Une crise européenne se transforme en guerre mondiale. Le conflit bouleverse les sociétés et entraîne la chute de plusieurs empires.',['1914 : attentat de Sarajevo et engrenage des alliances.','1916 : batailles de Verdun et de la Somme.','11 novembre 1918 : armistice avec l’Allemagne.'],'Première_Guerre_mondiale'],
['Seconde Guerre mondiale',1939,1945,'war','Monde','Une guerre mondiale oppose les Alliés aux puissances de l’Axe. Elle est marquée par la Shoah et des violences de masse.',['1939 : invasion de la Pologne par l’Allemagne nazie.','1944 : débarquement allié en Normandie.','1945 : capitulations de l’Allemagne puis du Japon.'],'Seconde_Guerre_mondiale'],
['Régime de Vichy',1940,1944,'politics','France','L’État français de Pétain est un régime autoritaire qui collabore avec l’Allemagne nazie et mène une politique antisémite.',['1940 : fin de la Troisième République.','Le régime participe aux persécutions et aux déportations.','1944 : Libération et rétablissement de la légalité républicaine.'],'Régime_de_Vichy'],
['Gouvernement provisoire',1944,1946,'politics','France','Le Gouvernement provisoire de la République française rétablit les institutions républicaines après la Libération.',['Le droit de vote des femmes est reconnu en 1944.','1945 : création de la Sécurité sociale.','1946 : adoption de la Constitution de la IVe République.'],'Gouvernement_provisoire_de_la_République_française'],
['Quatrième République',1946,1958,'politics','France','Un régime parlementaire accompagne la reconstruction, les débuts de la construction européenne et la décolonisation.',['1946 : nouvelle Constitution.','1957 : signature des traités de Rome.','1958 : crise algérienne et changement de régime.'],'Quatrième_République_(France)'],
['Guerre d’Algérie',1954,1962,'war','Algérie · France','Une guerre de décolonisation oppose les indépendantistes algériens, notamment le FLN, à la France. Elle aboutit à l’indépendance de l’Algérie.',['1er novembre 1954 : début de l’insurrection du FLN.','18 mars 1962 : signature des accords d’Évian.','Juillet 1962 : indépendance de l’Algérie.'],'Guerre_d’Algérie'],
['Cinquième République',1958,undefined,'politics','France','La Constitution de 1958 renforce le pouvoir exécutif. Le régime constitue le cadre institutionnel de la France contemporaine.',['4 octobre 1958 : promulgation de la Constitution.','1962 : réforme de l’élection présidentielle au suffrage universel direct.','2000 : passage du septennat au quinquennat.'],'Cinquième_République'],
['Tsunami de l’océan Indien',2004,undefined,'nature','Océan Indien','Le 26 décembre, un puissant séisme au large de Sumatra déclenche un tsunami qui frappe de nombreux pays riverains.',['Le séisme se produit sous l’océan, près de Sumatra.','Indonésie, Sri Lanka, Inde et Thaïlande sont notamment touchés.','La catastrophe accélère le développement des systèmes d’alerte.'],'Séisme_et_tsunami_de_2004_dans_l’océan_Indien'],
['Séisme et tsunami du Tōhoku',2011,undefined,'nature','Japon','Le 11 mars, un séisme majeur au large du Japon provoque un tsunami et conduit à l’accident nucléaire de Fukushima.',['La côte nord-est de Honshū est frappée.','Le tsunami submerge des villes et des infrastructures.','La catastrophe entraîne une réévaluation des risques côtiers et nucléaires.'],'Séisme_de_2011_de_la_côte_Pacifique_du_Tōhoku']
];
export const EVENTS: HistoricalEvent[] = entries.map(([title,start,end,category,location,summary,facts,article],index) => ({id:`event-${index}`,title,start,end,category,location,summary,facts,article: `https://fr.wikipedia.org/wiki/${encodeURIComponent(article.replaceAll('’', "'"))}`}));
export const CATEGORIES = [ {id:'war' as Category,label:'Guerres & conflits',icon:'↗',color:'#ba6551'}, {id:'politics' as Category,label:'Régimes politiques',icon:'♜',color:'#7065a5'}, {id:'nature' as Category,label:'Catastrophes naturelles',icon:'≈',color:'#438879'} ];
export const ERAS = [{id:'all',label:'Toute l’histoire',min:-Infinity,max:Infinity},{id:'ancient',label:'Antiquité',min:-Infinity,max:475},{id:'medieval',label:'Moyen Âge',min:476,max:1491},{id:'modern',label:'Époque moderne',min:1492,max:1788},{id:'contemporary',label:'Depuis 1789',min:1789,max:Infinity}];
